# This is a basic workflow to help you get started with Actions

name: Build front and deploy it to GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Install and Build 🔧 
        run: |
          npm install
          CI="" PUBLIC_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" npm run build
        working-directory: ./frontend

      - name: Push to Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages 
          folder: frontend/build
